apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-and-morty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rick-and-morty
  template:
    metadata:
      labels:
        app: rick-and-morty
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.29.0
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: rick-and-morty-cm
        name: content
