apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty
spec:
  ports:
  - nodePort: 30082
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: rick-and-morty
  type: NodePort
