apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty
spec:
  type: NodePort
  selector:
    app: rick-and-morty
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: placeholder
